apiVersion: v1
kind: Service
metadata:
  name: productservice1
spec:
  selector:
    app: productservice1
  ports:
    - protocol: TCP

      #Listeners
      port: 80

      #Processors
      targetPort: 8080
  type: NodePort
  